FROM mcr.microsoft.com/playwright:v1.61.1-noble

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --legacy-peer-deps && npx playwright install --with-deps chromium

COPY . .

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
